gerenciador_tarefas/models/tasks.py
from gerenciador_tarefas import db
from datetime import datetime, timezone
from flask_login import UserMixin

class Task(UserMixin, db.Model):
    __tablename__ = "Tasks"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text, nullable=False)
    due_date = db.Column(db.DateTime, nullable=False) # Data de vencimento da tarefa
    completed = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey("Users.id"), nullable=False)
    created_at  = db.Column(db.DateTime, default=datetime.now(timezone.utc)) # Data de criação


    def task_completed(self): # Tarefa finalizada
        self.completed = True

    def is_overdue(self): # Verifica se a tarefa está atrasada
        return datetime.now(timezone.utc) > self.due_date and not self.completed
    
    def delete_task(self):
        db.session.delete(self)
        db.commit()

    def set_due_date(self, new_date): # Muda a data do prazo 
        self.due_date = new_date
        db.session.commit()

    def __repr__(self):
        return f"Task {self.title}"

gerenciador_tarefas/forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Senha", validators=[DataRequired()])
    submit = SubmitField("Entrar")

gerenciador_tarefas/forms/task_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length

class CreateTaskForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=1, max=255)])
    description = TextAreaField("Description", validators=[DataRequired()])
    due_date = DateField("Due date", format="%Y-%m-%d" , validators=[DataRequired()])
    submit = SubmitField("Criar Tarefa")


class EditTaskForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=1, max=255)])
    description = TextAreaField("Description", validators=[DataRequired()])
    due_date = DateField("Due date", format="%Y-%m-%d" , validators=[DataRequired()])
    submit = SubmitField("Salvar Alterações")

gerenciador_tarefas/routes/auth_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from flask_login import login_required, logout_user, login_user
from gerenciador_tarefas.models.user import User
from gerenciador_tarefas import login_manager, db
from gerenciador_tarefas.forms import LoginForm, RegisterForm


usuario = Blueprint("usuario", __name__)

@usuario.route("/")
def principal():
    return render_template("index.html")


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@usuario.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if request.method == "POST":
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user and user.check_password(form.password.data):
                login_user(user)
                session["user"] = user.username
                return redirect(url_for("tasks.dashboard"))
            else:
                flash("Email ou senha inválidos", "danger")
        else:
            flash("Email ou senha inválidos", "danger")
    return render_template("login.html", form=form)


@usuario.route("/cadastro", methods=["GET", "POST"])
def cadastro():
    form = RegisterForm()
    if request.method == "POST":
        if form.validate_on_submit():
            if form.password.data == form.confirm_password.data:
                user_exists = User.query.filter_by(email=form.email.data).first()
                if user_exists is None:
                    user = User(username=form.username.data, email=form.email.data, password=form.password.data)

                    db.session.add(user)
                    db.session.commit()
                    login_user(user)
                    session["user"] = user.username
                    return redirect(url_for("tasks.dashboard"))
                else:
                    flash("⚠️ Este email já está em uso. Tente outro!", "danger")
            else:
                flash("❌ As senhas não conferem! Verifique e tente novamente.", "danger")
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f"Erro no campo {field}: {error}", "danger")
    return render_template("cadastro.html", form=form)


@usuario.route("/logout")
@login_required
def logout():
    logout_user()
    session.pop("user", None)
    return redirect(url_for("usuario.principal"))


@usuario.route("/<int:id>/delete")
@login_required
def delete_user(id):
    user = User.query.get_or_404(id)
    db.session.delete(user)
    db.session.commit()
    session.clear()
    flash("Conta excluida com sucesso!", "success")
    return redirect(url_for("usuario.principal"))

gerenciador_tarefas/routes/task_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from gerenciador_tarefas.models.tasks import Task
from gerenciador_tarefas import db
from datetime import datetime, date
from gerenciador_tarefas.forms import CreateTaskForm, EditTaskForm

tasks = Blueprint("tasks", __name__)


@tasks.route("/dashboard")
@login_required
def dashboard():
    user_tasks = Task.query.filter_by(user_id=current_user.id).all()
    current_date = datetime.today().date()
    return render_template("dashboard.html", tasks=user_tasks, current_date=current_date)


@tasks.route("/dashboard/new_task", methods=["GET", "POST"])
@login_required
def create_task():
    form = CreateTaskForm()
    if request.method == "POST":
        if form.validate_on_submit():

            new_task = Task(
                title=form.title.data,
                description=form.description.data,
                due_date=form.due_date.data,
                user_id = current_user.id
            ) 

            db.session.add(new_task)
            db.session.commit()
            return redirect(url_for("tasks.dashboard"))
    return render_template("task_form.html", form=form)


@tasks.route("/dashboard/<int:id>/delete/")
@login_required
def delete_task(id):
    task = Task.query.get_or_404(id)
    
    db.session.delete(task)
    db.session.commit()
    flash("Tarefa deletada com sucesso!", "success")
    return redirect(url_for("tasks.dashboard"))


@tasks.route("/dashboard/<int:id>/edit", methods=["GET", "POST"])
@login_required
def edit_task(id):
    task = Task.query.get_or_404(id)
    
    form = EditTaskForm(obj=task)
    if request.method == "POST":
        if form.validate_on_submit():
            task.title = form.title.data
            task.description = form.description.data
            task.due_date = form.due_date.data

        Task.query.filter_by(id=id).update({
            "title": task.title,
            "description": task.description,
            "due_date": task.due_date
        })
        db.session.commit()
        flash("A sua tarefa foi atualizada com sucesso!", "success")
        return redirect(url_for("tasks.dashboard"))
    return render_template("edit_task.html", form=form, task=task)
    

@tasks.route("/dashboard/completed/<int:id>", methods=["GET", "POST"])
def task_completed(id):
    task = Task.query.get_or_404(id)

    if task.user_id != current_user.id:
        flash("Você não tem permissão para finalizar essa tarefa!", "danger")
    
    task.completed = not task.completed

    db.session.commit()
    
    status_message = "finalizada" if task.completed else "marcada como incompleta"
    flash(f"Tarefa {status_message}!", "success" if task.completed else "danger")
    return redirect(url_for("tasks.dashboard"))

gerenciador_tarefas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Tarefas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/base.css')}}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand logo-custom" href="{{url_for('usuario.principal')}}"><img src="{{url_for('static', filename='img/logo.svg')}}" alt="Logo">Gerenciador de Tarefas</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link custom-link" href="{{url_for('tasks.dashboard') if session.get('user') else url_for('usuario.login')}}">Tarefas</a>
              </li>
            </ul>
          </div>
          <div class="d-flex">
            {% if 'user' in session %}
            <div class="dropdown perfil">
              <a class="btn btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{{url_for('static', filename='img/perfil.svg')}}" alt="Perfil">
                  {{ session['user'] }}
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
                  <li><a class="dropdown-item" href="{{url_for('usuario.logout')}}">Sair</a></li>
                  {% if current_user.is_authenticated %}
                    <li><a class="dropdown-item" href="{{url_for('usuario.delete_user', id=current_user.id)}}" onclick="return confirm('Tem certeza que deseja excluir sua conta?')">Excluir conta</a></li>
                  {% endif %}              
              </ul>            
            </div>
            {% else %}
              <a href="{{url_for('usuario.login')}}" class="btn btn-light me-3" style="display: flex; align-items: center;">Login</a>
              <a href="{{url_for('usuario.cadastro')}}" class="custom-button">Cadastrar</a>
            {% endif %}
          </div>
        </div>
      </nav>

      <div class="flash-container">
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                <div class="alert-container position-fixed" style="top: 80px; right: 20px; z-index: 1050;">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    </div>
      
      <div class="container">
        {% block conteudo %}

        {% endblock %}
      </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

gerenciador_tarefas/templates/cadastro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/cadastro.css')}}">
    <title>Cadastro</title>
</head>
<body>
    <div id="card">
        <h1>Cadastre-se</h1>

        <form action="{{url_for('usuario.cadastro')}}" method="POST">
            {{ form.hidden_tag() }}

        <div class="form-floating mb-3 custom-input">
            {{ form.username(class_="form-control", id="floatingInput")}}
            <label for="floatingInput">Nome de usuário</label>
        </div>

        <div class="form-floating mb-3 custom-input">
            {{ form.email(class_="form-control", id="floatingInput")}}
            <label for="floatingInput">Email</label>
        </div>

        <div class="form-floating mb-3 custom-input">
            {{ form.password(class_="form-control", id="floatingInput")}}
            <label for="floatingInput">Senha</label>
        </div>

        <div class="form-floating mb-3 custom-input">
            {{ form.confirm_password(class_="form-control", id="floatingInput")}}
            <label for="floatingInput">Confirme sua senha</label>
        </div>

        <div id="button">
            {{ form.submit(class_="cadastro") }}
        </div>
        
        <div class="container mt-4">
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    <div>
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
        </div>

        </form>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

gerenciador_tarefas/templates/dashboard.html
{% extends 'base.html' %}
{% block conteudo %}

<link rel="stylesheet" href="{{url_for('static', filename='css/dashboard.css')}}">

    <div class="container mt-4 card">
        <div class="d-flex justify-content-between mb-3">
            <h2 style="color: #FFF; margin: 0 auto;">Minhas Tarefas</h2>
            <form action="{{ url_for('tasks.create_task') }}">
                <button class="btn btn-primary" id="custom">Criar Tarefa</button>
            </form>
        </div>

        <table class="table table-dark table-hover">
            <thead>
                <tr>
                    <th scope="col" class="title">Tarefa</th>
                    <th scope="col" class="title">Validade</th>
                    <th scope="col" class="title">Status</th>
                    <th scope="col" class="title">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                    <tr>
                        <td class="{% if task.due_date.date() < current_date and not task.completed %}overdue{% else %}info{% endif %}">{{ task.title }}</td>
                        <td class="{% if task.due_date.date() < current_date and not task.completed %}overdue{% else %}info{% endif %}">
                            {{ task.due_date.strftime('%d/%m/%Y') }}
                        </td>
                        <td class="info">
                            <form action="{{ url_for('tasks.task_completed', id=task.id) }}" method="POST">
                                <button type="submit" class="btn btn-sm {% if task.completed %} btn-success-cor {% else %} btn-danger-cor {% endif %}">
                                    {% if task.completed %} Finalizada {% else %} Incompleta {% endif %}
                                </button>
                            </form>
                        </td>
                        <td class="info">
                            <a href="{{ url_for('tasks.edit_task', id=task.id) }}" class="btn btn-sm btn-primary-edit">
                                Editar
                            </a>
                            <a href="{{ url_for('tasks.delete_task', id=task.id) }}" class="btn btn-sm btn-danger-edit" onclick="return confirm('Você tem certeza de que deseja excluir essa tarefa ?');">
                                Excluir
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4" class="text-center">Nenhuma tarefa encontrada.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

gerenciador_tarefas/templates/edit_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Tarefa</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/edit_task.css')}}">
</head>
<body>

    <div class="container task">
        <h1 class="text-center" style="color: #F7FFF7;">Editar Tarefa</h1>

        <form method="POST" action="{{ url_for('tasks.edit_task', id=task.id) }}">
            {{ form.hidden_tag() }}
    
            <div class="form-floating mb-3">
                {{ form.title(class_="form-control", id="title") }}
                <label for="title">Tarefa</label>
            </div>
    
            <div class="form-floating mb-3">
                {{ form.description(class_="form-control", id="description") }}
                <label for="description">Descrição</label>
            </div>
    
            <div class="form-floating mb-3">
                {{ form.due_date(class_="form-control", id="due_date") }}
                <label for="due_date">Data de Vencimento</label>
            </div>
    
            <div id="button">
                {{ form.submit(class_="register") }}
            </div>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

gerenciador_tarefas/templates/index.html
{% extends 'base.html' %}
{% block conteudo %}
<link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">

<div id="card">
    <h1 style="text-align: center; padding: 10px;">Gerenciador de Tarefas</h1>

    <p> Organize seus deveres de forma simples e eficiente com o Gerenciador de Tarefas. O sistema foi projetado
        para ajudar você a monitorar suas responsabilidades diárias, definir suas prioridades e concluir suas tarefas de
        forma eficaz e organizada.</p>
    
    <p>As principais funcionalidades que o site terá são: </p>

    <ul>
        <li>Adicionar tarefas</li>
        <li>Editar tarefas</li>
        <li>Excluir tarefas</li>
        <li>Visualizar tarefas</li>
    </ul>
    
    <div class="d-flex justify-content-center button" id="button">
        <form action="{{url_for('tasks.dashboard') if session.get('user') else url_for('usuario.login')}}">
            <button class="btn btn-primary" id="iniciar">Gerencie suas tarefas</button>
        </form>
    </div>
    
    
</div>

{% endblock %}

gerenciador_tarefas/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/login.css')}}">
    <title>Login</title>
</head>
<body>
    <div id="card">
        <h1 style="text-align: center; color: #F7FFF7;">Entre com a sua conta</h1>

        <form action="{{url_for('usuario.login')}}" method="POST">
            {{ form.hidden_tag() }}


            <div class="form-floating mb-3 custom-input">
                {{ form.email(class_="form-control", id="floatingInput")}}
                <label for="floatingInput">Email</label>
            </div>
    
            <div class="form-floating mb-3">
                {{ form.password(class_="form-control", id="floatingInput")}}
                <label for="floatingPassword">Senha</label>
            </div>
    
            <div id="button">
                {{ form.submit(class_="login") }}
            </div>

            <div class="container">
                {% with messages = get_flashed_messages(with_categories=True) %}
                    {% if messages %}
                        <div>
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">{{ message }}</div>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endwith %}
            </div>

        </form>
        

        <div id="registrar">
            <p>Não possui uma conta ? <a href="{{url_for('usuario.cadastro')}}" id="cadastro">Cadastre-se</a></p>
        </div>

    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

gerenciador_tarefas/templates/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Tarefa</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/task_form.css')}}">
</head>
<body>
    <div class="container task">
        <h1 class="text-center" style="color: #F7FFF7;">Crie sua Tarefa</h1>

        <form method="POST" action="{{url_for('tasks.create_task')}}">
            {{ form.hidden_tag() }}

            <div class="form-floating mb-3">
                {{ form.title(class_="form-control", id="title")}}
                <label for="title">Tarefa</label>
            </div>

            <div class="form-floating mb-3">
                {{ form.description(class_="form-control", id="description")}}
                <label for="description">Descrição</label>
            </div>
    
            <div class="form-floating mb-3">
                {{ form.due_date(class_="form-control", id="due_date")}}
                <label for="due_date">Data de Vencimento</label>
            </div>

            <div id="button">
                {{ form.submit(class_="register") }}
            </div>

        </form>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>